# Generated by Django 5.1.15 on 2026-09-30 16:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_institutionsetting_block_report_cards_on_debt_and_more'),
        ('students', '0005_expedientedocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Concepto')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('recurrence', models.CharField(choices=[('MONTHLY', 'Mensual (Pensión recurrente)'), ('ANNUAL', 'Anual (Matrícula / Seguro)'), ('ONE_TIME', 'Única Vez / Eventual')], default='MONTHLY', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Predeterminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Concepto de Cobro',
                'verbose_name_plural': 'Conceptos de Cobro',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes correspondiente (1-12)')),
                ('due_date', models.DateField(verbose_name='Fecha Límite de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a Pagar')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Abonado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagada / Paz y Salvo'), ('OVERDUE', 'Vencida / En Mora'), ('WAIVED', 'Exonerada / Beca')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones_financieras', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='finance.feeconcept', verbose_name='Concepto de Cobro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones_financieras', to='students.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Obligación Financiera',
                'verbose_name_plural': 'Obligaciones Financieras',
                'ordering': ['due_date', 'student__user__last_name'],
                'unique_together': {('student', 'academic_year', 'concept', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Recaudado')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo / Caja'), ('TRANSFER', 'Transferencia Bancaria'), ('CARD', 'Tarjeta Débito / Crédito'), ('PSE', 'Pasarela Online / PSE')], default='CASH', max_length=20, verbose_name='Medio de Pago')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Recibo / Factura')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Secretaría / Cajero')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finance.studentfeeobligation', verbose_name='Obligación Pagada')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
