# Generated by Django 5.1.15 on 2026-09-30 14:02

import apps.students.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_institutionsetting_block_report_cards_on_debt_and_more'),
        ('students', '0004_enrollment_admission_requirement_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ADMISSION', '1. Admisión e Ingreso'), ('ACADEMIC', '2. Académico'), ('CONVIVENCIA', '3. Convivencia y Disciplina'), ('ADMINISTRATIVE', '4. Administrativo y Financiero')], db_index=True, max_length=20, verbose_name='Categoría del Expediente')),
                ('document_type', models.CharField(choices=[('REGISTRO_CIVIL', 'Registro Civil de Nacimiento'), ('TARJETA_IDENTIDAD', 'Tarjeta de Identidad / Cédula / DNI'), ('CARNET_VACUNAS', 'Carnet de Vacunación'), ('CERTIFICADO_EPS', 'Certificado de Afiliación a EPS'), ('CERTIFICADO_ESTUDIO_ANT', 'Certificado de Estudios de Años Anteriores'), ('FOTO_DOCUMENTO', 'Fotografía Digital Tipo Documento'), ('BOLETIN_OFICIAL', 'Boletín Oficial de Calificaciones'), ('CERTIFICADO_ESTUDIO', 'Certificado Oficial de Estudios'), ('ACTA_GRADO', 'Acta de Grado / Diploma'), ('INFORME_PEDAGOGICO', 'Informe Psicopedagógico / Inclusión (PIAR)'), ('ACTA_COMPROMISO', 'Acta de Compromiso Convivencial'), ('DESCARGOS_DISCIPLINA', 'Formato de Descargos Disciplinarios'), ('CITACION_ACUDIENTE', 'Citación Formal a Acudiente'), ('EXCUSA_MEDICA', 'Incapacidad / Excusa Médica Validada'), ('CONTRATO_MATRICULA', 'Contrato de Matrícula y Prestación de Servicios'), ('PAGARE', 'Pagaré y Carta de Instrucciones'), ('PAZ_Y_SALVO', 'Paz y Salvo Institucional'), ('AUTORIZACION_DATOS', 'Autorización de Tratamiento de Datos (Habeas Data)'), ('OTRO', 'Otro Documento Institucional')], db_index=True, default='OTRO', max_length=30, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=150, verbose_name='Título Descriptivo del Documento')),
                ('file', models.FileField(upload_to=apps.students.models.expediente_upload_path, verbose_name='Archivo Digital (PDF, JPG, PNG)')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='¿Verificado Oficialmente por Secretaría?')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Verificación')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Subida')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones / Número de Folio Físico')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediente_documentos', to='courses.academicyear', verbose_name='Año Lectivo Asociado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_documentos', to='students.studentprofile', verbose_name='Estudiante')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_expediente_docs', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_expediente_docs', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario que Verificó')),
            ],
            options={
                'verbose_name': 'Documento del Expediente',
                'verbose_name_plural': 'Documentos del Expediente (Carpeta Perpetua)',
                'ordering': ['category', '-uploaded_at'],
                'indexes': [models.Index(fields=['student', 'category'], name='students_ex_student_106e6b_idx'), models.Index(fields=['student', 'document_type'], name='students_ex_student_0c2d3c_idx')],
            },
        ),
    ]
