# Generated by Django 5.1.15 on 2026-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_gradelevel_level_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='school_scope',
            field=models.CharField(choices=[('COMPLETA', 'Colegio Completo (Transición, Primaria y Secundaria/Media)'), ('PRIMARIA', 'Solo Primaria (Transición, 1° a 5°)'), ('SECUNDARIA', 'Solo Secundaria y Media (6° a 11°)')], default='COMPLETA', help_text='Aplica para Colegios: Define si ofrece Primaria, Secundaria o Ambos niveles.', max_length=20, verbose_name='Enfoque del Colegio'),
        ),
    ]
