# Generated by Django 5.1.15 on 2026-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_institutionsetting_school_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo de Contacto Institucional'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Foto del colegio o estudiantes que aparece en el fondo del login.', null=True, upload_to='institution/hero/', verbose_name='Imagen Hero de la Página de Login'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo que aparecerá en el login y la barra lateral.', null=True, upload_to='institution/logos/', verbose_name='Logo Institucional (PNG/SVG recomendado)'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='primary_color',
            field=models.CharField(default='#7c3aed', help_text='Color principal de la institución. Ej: #7c3aed (morado ACADEMIX), #1b4332 (verde), #1e3a8a (azul).', max_length=7, verbose_name='Color Primario (hex)'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='secondary_color',
            field=models.CharField(default='#c4b5fd', help_text='Color de acentos y fondos claros. Suele ser una versión más clara del color primario.', max_length=7, verbose_name='Color Secundario / Pastel (hex)'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='website_url',
            field=models.URLField(blank=True, default='', verbose_name='Sitio Web Oficial'),
        ),
    ]
