# Generated by Django 5.1.15 on 2026-09-30 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_institution_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='block_report_cards_on_debt',
            field=models.BooleanField(default=False, help_text='Bloquea la descarga de boletines a familias con saldo pendiente. En colegios oficiales se fuerza a inactivo por ley.', verbose_name='Bloqueo de Boletines por Morosidad Económica'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='consecutive_resolution',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Resolución de Reconocimiento Oficial / NIT'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='dane_code',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Código DANE de la Sede Educativa'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='enable_gratuity_control',
            field=models.BooleanField(default=False, help_text='Aplica para Colegios Públicos: Garantiza gratuidad universal en matrículas y certificados.', verbose_name='Control de Gratuidad Estatal'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='enable_online_admissions',
            field=models.BooleanField(default=True, verbose_name='Habilitar Admisiones en Línea y Contratos'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='enable_pae_module',
            field=models.BooleanField(default=False, help_text='Control diario de cupos, entregas de refrigerios y beneficiarios PAE.', verbose_name='Módulo de Alimentación Escolar (PAE / Refrigerios)'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='enable_payment_gateway',
            field=models.BooleanField(default=False, verbose_name='Habilitar Pasarela de Pagos en Línea (PSE/Wompi/Stripe)'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='enable_simat_integration',
            field=models.BooleanField(default=False, verbose_name='Integración y Exportación de Archivos Oficiales SIMAT (MEN)'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='enable_tuition_billing',
            field=models.BooleanField(default=True, help_text='Habilita el módulo de cobro recurrente para instituciones privadas.', verbose_name='Habilitar Facturación de Matrículas y Pensiones'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='grade_decimal_places',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Cifras Decimales en Notas'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='grading_scale_type',
            field=models.CharField(choices=[('NUMERIC_5', 'Cuantitativa Tradicional (1.00 - 5.00)'), ('NUMERIC_100', 'Cuantitativa Centesimal (0.00 - 100.00)'), ('NUMERIC_10', 'Cuantitativa Decimal (1.00 - 10.00)'), ('CONCEPTUAL_MEN', 'Conceptual Oficial MEN (Superior, Alto, Básico, Bajo)')], default='NUMERIC_5', max_length=20, verbose_name='Escala de Calificación Activa'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='max_grade',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Nota Máxima Posible'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='min_grade',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Nota Mínima Posible'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='passing_grade',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Nota Mínima Aprobatoria'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='period_structure',
            field=models.CharField(choices=[('PERIODS_4', '4 Periodos Académicos (25% c/u - Estándar Oficial)'), ('TRIMESTERS_3', '3 Trimestres (33.33% c/u)'), ('SEMESTERS_2', '2 Semestres (50% c/u)')], default='PERIODS_4', max_length=20, verbose_name='Estructura de Periodos del Año'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='sector_mode',
            field=models.CharField(choices=[('PUBLICO', 'Colegio Oficial / Público (Estatal - Gratuidad)'), ('PRIVADO', 'Colegio Privado / No Oficial')], db_index=True, default='PRIVADO', help_text='Pilar 1 SaaS Híbrido: Determina si rigen normas estatales (gratuidad, SIMAT, PAE) o comerciales (facturación, admisiones).', max_length=15, verbose_name='Sector Institucional'),
        ),
    ]
