# Generated by Django 5.1.15 on 2026-09-30 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_institutionsetting_block_report_cards_on_debt_and_more'),
        ('periods', '0001_initial'),
        ('students', '0005_expedientedocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(choices=[('TIPO_I', 'Situación Tipo I (Falta Leve / Formativa)'), ('TIPO_II', 'Situación Tipo II (Falta Grave / Afectación Convivencial)'), ('TIPO_III', 'Situación Tipo III (Falta Gravísima / Delito o Violencia)'), ('POSITIVA', 'Reconocimiento Convivencial (Mérito / Felicitación)')], default='TIPO_I', max_length=20, verbose_name='Tipificación de la Situación')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de los Hechos')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora aproximada')),
                ('location', models.CharField(default='Aula de Clase', max_length=150, verbose_name='Lugar / Contexto de los hechos')),
                ('title', models.CharField(max_length=200, verbose_name='Título o Resumen de la Situación')),
                ('description', models.TextField(verbose_name='Descripción Detallada de los Hechos')),
                ('student_disclaimer', models.TextField(blank=True, null=True, verbose_name='Descargos / Versión del Estudiante')),
                ('pedagogical_commitment', models.TextField(blank=True, null=True, verbose_name='Acción Restaurativa y Compromiso Pedagógico')),
                ('parent_notified', models.BooleanField(default=False, verbose_name='Notificado al Acudiente')),
                ('parent_acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Firma del Acudiente')),
                ('parent_signature_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de quien firma como Acudiente')),
                ('parent_comments', models.TextField(blank=True, null=True, verbose_name='Observaciones o Compromiso del Acudiente')),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta (Pendiente de descargos o firma)'), ('SEGUIMIENTO', 'En Seguimiento Pedagógico'), ('CERRADA', 'Cerrada (Compromisos cumplidos)'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20, verbose_name='Estado de la Anotación')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_disciplinarias', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anotaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Docente / Directivo que registra')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones_disciplinarias', to='periods.academicperiod', verbose_name='Periodo Lectivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_disciplinarias', to='students.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Anotación del Observador',
                'verbose_name_plural': 'Anotaciones del Observador',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
