# Generated by Django 5.1.15 on 2026-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_options_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marca la asignatura representativa de este grupo (Historia, Arte o Deporte).', verbose_name='¿Es la asignatura principal de su categoría?'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('PRINCIPAL', 'Materia Principal'), ('HUMANISTICA', 'Materia Humanística'), ('HISTORIA', 'Historia y Ciencias Sociales'), ('ARTE', 'Arte y Cultura'), ('DEPORTE', 'Deporte y Educación Física')], default='PRINCIPAL', max_length=20, verbose_name='Agrupación / Categoría'),
        ),
    ]
