# Generated by Django 5.1.15 on 2026-09-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_split_categories_historia_arte_deporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectnorm',
            options={'ordering': ['subject', 'order', 'code'], 'verbose_name': 'Resultado de Aprendizaje (RAP)', 'verbose_name_plural': 'Resultados de Aprendizaje (RAPs)'},
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='competency',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Competencia General'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Dimensión'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Dominio'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='evidence',
            field=models.TextField(blank=True, default='', verbose_name='Elaborar (Evidencia de Aprendizaje / Producto)'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='hacer',
            field=models.TextField(blank=True, default='', verbose_name='Hacer (Procedimental / Desempeño)'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='indicator',
            field=models.TextField(blank=True, default='', verbose_name='Indicador de Logro / Desempeño'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='saber',
            field=models.TextField(blank=True, default='', verbose_name='Saber (Cognitivo / Conceptual)'),
        ),
        migrations.AddField(
            model_name='subjectnorm',
            name='ser',
            field=models.TextField(blank=True, default='', verbose_name='Ser (Actitudinal / Convivencial)'),
        ),
        migrations.AlterField(
            model_name='subjectnorm',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código de Norma / RAP'),
        ),
        migrations.AlterField(
            model_name='subjectnorm',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción de la Competencia / Estándar'),
        ),
        migrations.AlterField(
            model_name='subjectnorm',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del RAP / Competencia'),
        ),
    ]
