# Generated by Django 5.1.15 on 2026-09-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_add_topic_to_evaluation_criterion'),
        ('subjects', '0005_alter_subjectnorm_options_subjectnorm_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriterion',
            name='norm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_criteria', to='subjects.subjectnorm', verbose_name='RAP Curricular Asociado'),
        ),
    ]
