# Generated by Django 5.1.15 on 2026-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='is_group_director',
            field=models.BooleanField(default=False, help_text='Si está marcado, este docente es el director de grupo del curso y puede acceder a los boletines.', verbose_name='¿Director de Grupo?'),
        ),
    ]
