# Generated by Django 5.1.15 on 2026-09-30 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador / Dispositivo (User Agent)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('INSERT', 'Creación (INSERT)'), ('UPDATE', 'Modificación (UPDATE)'), ('DELETE', 'Eliminación (DELETE)'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('FAILED_LOGIN', 'Intento Fallido de Inicio de Sesión'), ('PERIOD_CLOSE', 'Cierre de Periodo Académico'), ('GRADE_OVERRIDE', 'Modificación Extraordinaria de Nota'), ('OBSERVATION_DELETED', 'Eliminación de Observador / Convivencia'), ('ATTENDANCE_OVERRIDE', 'Modificación de Asistencia Docente'), ('ENROLLMENT_ALTERED', 'Alteración de Matrícula o Estado de Alumno'), ('OFFICIAL_REPORT_EXPORT', 'Exportación de Reporte Oficial / SIMAT'), ('SECURITY_ALERT', 'Alerta Crítica de Seguridad'), ('FINANCIAL_TRANSACTION', 'Transacción o Modificación Financiera'), ('CONFIG_CHANGE', 'Cambio en Parametrización Institucional')], db_index=True, max_length=30, verbose_name='Acción Realizada'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
    ]
